Content:

  NewsCenter:
    DmNewsArticle:
      name:         News
      page:         true
      components:
        list:
          filters: [DmNewsCategory]
        listSide:
          filters: [DmNewsCategory]
        show:

    DmNewsLetter:
      name:         Newsletter

    DmNewsSubscriber:
      name:         Subscriber
      components:
        form:       { name: "Subscription" }

    DmNewsCategory:
      name:         Category|Categories
      admin: true

