<?php

/**
 * PluginDmNewsLetterCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsLetterCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsLetterCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsLetterCategory');
    }
}