<?php

/**
 * PluginDmNewsLetterTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsLetterTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsLetterTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsLetter');
    }
}