<?php

/**
 * PluginDmNewsCategoryArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsCategoryArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsCategoryArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsCategoryArticle');
    }
}