<?php

/**
 * PluginDmNewsSubscriberTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsSubscriberTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsSubscriberTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsSubscriber');
    }
}