<?php

/**
 * PluginDmNewsLetterArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsLetterArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsLetterArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsLetterArticle');
    }
}