<?php

/**
 * PluginDmNewsSubscriberCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsSubscriberCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsSubscriberCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsSubscriberCategory');
    }
}