<?php

/**
 * PluginDmNewsLetter
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 26 2010-10-02 18:35:29Z tohms $
 */
abstract class PluginDmNewsLetter extends BaseDmNewsLetter
{

}