<?php

/**
 * PluginDmNewsArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsArticleTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsArticle');
    }
}