<?php

/**
 * PluginDmNewsCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsCategory');
    }
}