<?php

/**
 * PluginDmNewsCategoryArticlesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmNewsCategoryArticlesTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmNewsCategoryArticlesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmNewsCategoryArticles');
    }
}