DmNewsArticle:
  actAs:
    DmGallery:
    I18n:
      fields:             [ title, summary, body, is_active ]
      actAs:
        Timestampable:
        DmBlameable:
  columns:
    title:                { type: string(120), notnull: true }
    summary:              { type: string(2000), notnull: true }
    body:                 { type: clob, extra: markdown }
    image:                { type: integer }
    author:               { type: integer, notnull: true }
    newsletter:           { type: integer }
    is_active:            { type: boolean, notnull: true, default: false }
  relations:
    Newsletters:
      class:              DmNewsLetter
      refClass:           DmNewsLetterArticle
      local:              article_id
      foreign:            newsletter_id
      type:               many
      foreignType:        many
      foreignAlias:       Articles
    Categories:
      class:              DmNewsCategory
      refClass:           DmNewsCategoryArticle
      local:              article_id
      foreign:            category_id
      type:               many
      foreignType:        many
      foreignAlias:       Articles

DmNewsLetter:
  actAs:
    I18n:
      fields:             [ subject ]
      actAs:
        Timestampable:
  columns:
    subject:              { type: string(120), notnull: true }
    sent_at:              { type: timestamp }
  relations:
    Categories:
      class:              DmNewsCategory
      refClass:           DmNewsLetterCategory
      local:              newsletter_id
      foreign:            category_id
      type:               many
      foreignType:        many
      foreignAlias:       NewsLetters

DmNewsLetterArticle:
  columns:
    newsletter_id:           { type: integer, primary: true }
    article_id:              { type: integer, primary: true }

DmNewsSubscriber:
  actAs:
    Timestampable:
  columns:
    first_name:           { type: string(120), notnull: true }
    last_name:            { type: string(120), notnull: true }
    email:                { type: string(255), notnull: true, unique: true }
    is_confirmed:         { type: boolean, notnull: true, default: false }
  relations:
    Categories:
      class:              DmNewsCategory
      refClass:           DmNewsSubscriberCategory
      local:              subscriber_id
      foreign:            category_id
      type:               many
      foreignType:        many
      foreignAlias:       Subscribers

DmNewsCategory:
  actAs:
    DmSortable:
    I18n:
      fields:             [ title, is_active ]
      actAs:
        Timestampable:
  columns:
    title:                { type: string(255), notnull: true }
    is_active:            { type: boolean, notnull: true, default: false }
    is_registrable:       { type: boolean, notnull: true, default: false }

DmNewsSubscriberCategory:
  columns:
    subscriber_id:        { type: integer, primary: true }
    category_id:          { type: integer, primary: true }
  relations:
    Subscriber:
      class: DmNewsSubscriber
      local: subscriber_id
      foreign: id

DmNewsCategoryArticle:
  columns:
    category_id:          { type: integer, primary: true }
    article_id:           { type: integer, primary: true }

DmNewsLetterCategory:
  columns:
    newsletter_id:        { type: integer, primary: true }
    category_id:          { type: integer, primary: true }
