generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmNewsCategory
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: dm_news_category
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        subscribers_list:
          label: Subscribers
      list:
        display:
          - '=title'
          - articles_list
          - subscribers_list
          - news_letters_list
          - is_active
          - created_at
          - updated_at
        sort:
          - title
          - asc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: true
      filter:
        display:
          - title
          - is_active
          - articles_list
          - subscribers_list
          - news_letters_list
          - created_at
          - updated_at
      form:
        display:
          NONE: [title, is_active, position]
          Subscribers: [subscribers_list]
          Publication: [articles_list, news_letters_list]
        class: DmNewsCategoryAdminForm
        fields: {  }
      edit: ~
      new: ~
